Move domain module into its own crate
Some (three) Froms have been inlined because of errors like:

error[E0117]: only traits defined in the current crate can be
implemented for arbitrary types
  --> server/src/database/repository/./diesel/item_query.rs:25:1
   |
25 | impl From<ItemAndMasterList> for Item {
   | ^^^^^-----------------------^^^^^----
   | |    |                           |
| |    |                           `domain::item::Item` is not
defined in the current crate
| |    this is not defined in the current crate because tuples are
always foreign
   | impl doesn't use only types from inside the current crate
   |
   = note: define and implement a trait or new type instead